app = "aterra-clip"

[build]
  dockerfile = "Dockerfile"

[env]
  MODEL_ID = "openai/clip-vit-base-patch32"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
